name: Code Quality and Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openpyxl

      - name: Run Trivy scan (all)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'
          ignore-unfixed: true
          scanners: 'vuln,secret,config,license'

      - name: Convert Trivy results to Excel
        run: |
          python .github/scan_to_excel.py

      - name: Upload Excel artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: scan-results.xlsx
